version: "3.5"

services:
  postgres:
    image: library/postgres:10.7
    container_name: keycloak_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/tmp/init.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: always
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: postgres
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    depends_on:
      - postgres
    ports:
      - 8082:8080
      - 8443:8443

volumes:
  postgres_data:

